services:
  app_gl:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /opt/docker_volumes/mysql_data
        target: /var/lib/mysql
    command: gunicorn --bind 0.0.0.0:5000 --workers=4 --timeout=300 wsgi:app
    environment:
      - FLASK_ENV=production

      # Uncomment the lines below and tweak its values to customize the app
      # - COMPANY_NAME=Custom Name
      # - COMPANY_COLOR=#8a1237

    restart: unless-stopped

  db_gl:
    image: mysql:8.0.42
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_USER: gestaolegal
      MYSQL_PASSWORD: gestaolegal
      MYSQL_DATABASE: gestaolegal
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: bind
        source: /opt/docker_volumes/mysql_data
        target: /var/lib/mysql

  adminer_gl:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  mysql_data:
    driver: local

