services:
  app_gl:
    build: .
    image: gestao_legal_app
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /code

    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  db_gl:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_USER: gestaolegal
      MYSQL_PASSWORD: gestaolegal
      MYSQL_DATABASE: gestaolegal
    ports:
      - '3306:3306'
    expose:
      - '3306'

  adminer_gl:
      image: adminer
      restart: unless-stopped
      ports:
        - '8080:8080'
