services:
  app_gl:
    build: .
    entrypoint: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    environment:
      - FLASK_ENV=development
      - FLASK_APP=gestaolegal.wsgi:app
    develop:
      watch:
        - action: sync
          path: ./gestaolegal/
          target: /code/gestaolegal/
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock

  db_gl:
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:v1.24
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
    driver: local 

