services:
  app_gl:
    command: flask run --host=0.0.0.0 

  db_gl:
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:v1.24
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
    driver: local
