services:
  app_gl:
    build: .
    entrypoint: ["flask", "--app", "gestaolegal", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=abcdefghijklmnopqrstuvwxyz0123456789
      - DB_USER=gestaolegal
      - DB_PASSWORD=gestaolegal
      - DB_HOST=db_gl
      - DB_NAME=gestaolegal
      - COMPANY_NAME=Gestão Legal
      - COMPANY_COLOR=#1758ac
      - ADMIN_EMAIL=admin@gl.com
      - ADMIN_PASSWORD=123456
      # Optional: Email Configuration
      # - MAIL_SERVER=smtp.gmail.com
      # - MAIL_PORT=465
      # - MAIL_USE_SSL=True
      # - MAIL_USERNAME=your-email@gmail.com
      # - MAIL_PASSWORD=your-email-password
    develop:
      watch:
        - action: sync
          path: ./gestaolegal/
          target: /code/gestaolegal/
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock

  db_gl:
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_USER: gestaolegal
      MYSQL_PASSWORD: gestaolegal
      MYSQL_DATABASE: gestaolegal
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:v1.24
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
    driver: local 

