[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gestaolegal"
version = "0.1.0"
description = "Sistema de Gestão Legal"
requires-python = ">=3.11"
dependencies = [
    "aiosmtpd==1.4.6",
    "alembic==1.4.1",
    "astroid==2.2.5",
    "bcrypt==3.1.7",
    "blinker==1.4",
    "certifi==2019.11.28",
    "cffi==1.15.1",
    "click==8.0.1",
    "colorama==0.4.1",
    "cryptography==42.0.0",
    "flask==1.1.1",
    "flask-bcrypt==0.7.1",
    "flask-login==0.5.0",
    "flask-mail==0.9.1",
    "flask-marshmallow==0.13.0",
    "flask-migrate==2.5.3",
    "flask-paginate==0.6.0",
    "flask-sqlalchemy==2.4.1",
    "flask-wtf==0.14.3",
    "gunicorn==20.0.4",
    "isort==4.3.15",
    "itsdangerous==1.1.0",
    "jinja2==3.0.3",
    "lazy-object-proxy==1.3.1",
    "mako==1.1.2",
    "markupsafe==2.0.1",
    "marshmallow==3.6.1",
    "marshmallow-sqlalchemy==0.23.1",
    "pycparser==2.20",
    "pylint==2.3.1",
    "pymysql==0.9.3",
    "python-dateutil==2.8.1",
    "python-editor==1.0.4",
    "pytz==2021.1",
    "rope==0.17.0",
    "six==1.14.0",
    "sqlalchemy==1.3.15",
    "toml==0.10.1",
    "werkzeug==2.0.0",
    "wincertstore==0.2",
    "wrapt==1.11.1",
    "wtforms==2.2.1",
]

[tool.setuptools]
packages = ["gestaolegal"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
adopts = "-v"

[project.optional-dependencies]
dev = [
    "pytest-base-url>=2.1.0",
    "pytest-playwright==0.7.0",
    "aiosmtpd==1.4.6",
    "pytest-base-url",
]
