FROM python:3.11-bookworm

RUN python -m pip install --upgrade pip
WORKDIR /code

RUN pip install playwright && \
    playwright install --with-deps

COPY requirements.txt .
COPY tests/requirements.txt tests/requirements.txt

RUN pip install -r requirements.txt
RUN pip install -r tests/requirements.txt

COPY . .

ENTRYPOINT ["pytest", "--base-url", "http://app_gl:5000", "tests/", "-v"]
