FROM python:3.11-bookworm

RUN python -m pip install --upgrade pip
WORKDIR /code

RUN pip install playwright && \
    playwright install --with-deps

COPY pyproject.toml .

COPY . .

RUN pip install .[dev]

ENTRYPOINT ["pytest", "--browser-channel", "chromium", "--base-url", "http://app_gl:5000", "tests/", "-v"]
