import os
from io import BytesIO
from typing import Any

import pytest
from flask import Flask
from flask.testing import FlaskClient
from werkzeug.datastructures import FileStorage

from gestaolegal.exceptions import ValidationException
from gestaolegal.repositories.evento_repository import EventoRepository
from gestaolegal.services import private_file_storage
from gestaolegal.services.evento_service import EventoService
from tests.api.conftest import get_success_data


def test_create_evento_without_file(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test evento creation with multipart/form-data but no file"""
    # First create a caso
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create evento without file using multipart/form-data
    evento_data = {
        "tipo": "Audiência",
        "data_evento": "2024-06-20",
        "descricao": "Audiência de conciliação",
        "status": "true",
    }

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=evento_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 201
    data = get_success_data(response)
    assert data is not None
    assert data["tipo"] == "Audiência"
    assert data["descricao"] == "Audiência de conciliação"
    assert "data_evento" in data
    assert "2024" in data["data_evento"]


def test_create_evento_with_file(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test evento creation with file upload"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create evento with file
    file_content = b"Este eh um arquivo de teste para evento"
    evento_data = {
        "tipo": "Juntada de Documentos",
        "data_evento": "2024-07-15",
        "descricao": "Juntada de procuração",
        "status": "true",
        "arquivo": (BytesIO(file_content), "procuracao.pdf"),
    }

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=evento_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 201
    data = get_success_data(response)
    assert data is not None
    assert data["tipo"] == "Juntada de Documentos"
    assert data["descricao"] == "Juntada de procuração"
    assert data["arquivo"] is not None
    assert "procuracao.pdf" in data["arquivo"]


def test_create_evento_with_num_evento(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test evento creation - num_evento is auto-generated by backend"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    evento_data = {"tipo": "Petição", "data_evento": "2024-08-10", "status": "true"}

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=evento_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 201
    data = get_success_data(response)
    assert data is not None
    # num_evento is auto-generated by backend based on count
    assert data["num_evento"] == 1


def test_create_evento_with_usuario_responsavel(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test evento creation with id_usuario_responsavel"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    evento_data = {
        "tipo": "Tarefa",
        "data_evento": "2024-09-05",
        "descricao": "Revisar petição inicial",
        "id_usuario_responsavel": "1",
        "status": "true",
    }

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=evento_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 201
    data = get_success_data(response)
    assert data is not None
    assert data["id_usuario_responsavel"] == 1


def test_update_evento_without_file_change(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test evento update without changing the file"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create evento
    create_data = {
        "tipo": "Audiência",
        "data_evento": "2024-10-01",
        "descricao": "Audiência inicial",
        "status": "true",
    }

    create_response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=create_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )
    assert create_response.status_code == 201
    create_evento_data = get_success_data(create_response)
    assert create_evento_data is not None
    evento_id = create_evento_data["id"]

    # Update only text fields
    update_data = {
        "descricao": "Audiência inicial - ADIADA",
        "data_evento": "2024-10-15",
    }

    response = client.put(
        f"/api/caso/{caso_id}/eventos/{evento_id}",
        data=update_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    data = get_success_data(response)
    assert data is not None
    assert data["descricao"] == "Audiência inicial - ADIADA"
    assert data["tipo"] == "Audiência"  # Original value preserved


def test_update_evento_with_new_file(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test evento update with new file upload"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create evento with file
    original_file = b"Arquivo original"
    create_data = {
        "tipo": "Juntada",
        "data_evento": "2024-11-01",
        "status": "true",
        "arquivo": (BytesIO(original_file), "original.pdf"),
    }

    create_response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=create_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )
    assert create_response.status_code == 201
    create_evento_data = get_success_data(create_response)
    assert create_evento_data is not None
    evento_id = create_evento_data["id"]

    # Update with new file
    new_file = b"Arquivo atualizado"
    update_data = {"arquivo": (BytesIO(new_file), "atualizado.pdf")}

    response = client.put(
        f"/api/caso/{caso_id}/eventos/{evento_id}",
        data=update_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    data = get_success_data(response)
    assert data is not None
    assert "atualizado.pdf" in data["arquivo"]


def test_evento_date_parsing_from_string(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test that data_evento is parsed correctly from ISO string"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    evento_data = {
        "tipo": "Prazo",
        "data_evento": "2024-12-25",
        "descricao": "Prazo para contestação",
        "status": "true",
    }

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=evento_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 201
    data = get_success_data(response)
    assert data is not None
    # Backend returns dates in HTTP date format (RFC 2822), not ISO
    assert "data_evento" in data
    assert "2024" in data["data_evento"]
    assert "Dec" in data["data_evento"] or "12" in data["data_evento"]


def test_get_evento_by_id(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test retrieving a specific evento"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create evento
    create_data = {
        "tipo": "Sentença",
        "data_evento": "2024-05-30",
        "descricao": "Sentença publicada",
        "status": "true",
    }

    create_response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=create_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )
    assert create_response.status_code == 201
    create_evento_data = get_success_data(create_response)
    assert create_evento_data is not None
    evento_id = create_evento_data["id"]

    # Get evento by id
    response = client.get(
        f"/api/caso/{caso_id}/eventos/{evento_id}", headers=auth_headers
    )

    assert response.status_code == 200
    data = get_success_data(response)
    assert data is not None
    assert data["id"] == evento_id
    assert data["tipo"] == "Sentença"
    assert data["descricao"] == "Sentença publicada"


def test_get_eventos_by_caso(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test listing all eventos for a caso"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create multiple eventos
    for i in range(3):
        evento_data = {
            "tipo": f"Evento {i + 1}",
            "data_evento": "2024-03-15",
            "status": "true",
        }
        create_response = client.post(
            f"/api/caso/{caso_id}/eventos",
            data=evento_data,
            headers=auth_headers,
            content_type="multipart/form-data",
        )
        assert create_response.status_code == 201
        assert get_success_data(create_response) is not None

    # Get all eventos for caso
    response = client.get(f"/api/caso/{caso_id}/eventos", headers=auth_headers)

    assert response.status_code == 200
    data = get_success_data(response)
    assert data is not None
    assert isinstance(data, dict)
    assert "items" in data
    assert "total" in data
    assert "page" in data
    assert "per_page" in data
    assert isinstance(data["items"], list)
    assert len(data["items"]) >= 3
    assert data["total"] >= 3


def test_download_evento_file(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Test downloading an evento file"""
    caso_response = client.post(
        "/api/caso/", json=sample_caso_data, headers=auth_headers
    )
    assert caso_response.status_code == 201
    caso_data = get_success_data(caso_response)
    assert caso_data is not None
    caso_id = caso_data["id"]

    # Create evento with file
    file_content = b"Conteudo do arquivo para download"
    evento_data = {
        "tipo": "Documento",
        "data_evento": "2024-04-20",
        "status": "true",
        "arquivo": (BytesIO(file_content), "documento.pdf"),
    }

    create_response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data=evento_data,
        headers=auth_headers,
        content_type="multipart/form-data",
    )
    assert create_response.status_code == 201
    create_evento_data = get_success_data(create_response)
    assert create_evento_data is not None
    evento_id = create_evento_data["id"]

    # Download file
    response = client.get(
        f"/api/caso/{caso_id}/eventos/{evento_id}/download", headers=auth_headers
    )

    assert response.status_code == 200
    assert response.data == file_content


# ---------------------------------------------------------------------------
# Exclusão e filtro por tipo (paridade com a v2)
# ---------------------------------------------------------------------------


def _criar_caso(client: FlaskClient, headers: dict[str, str], caso_data: dict[str, Any]) -> int:
    response = client.post("/api/caso/", json=caso_data, headers=headers)
    assert response.status_code == 201
    return get_success_data(response)["id"]


def _criar_evento(
    client: FlaskClient, headers: dict[str, str], caso_id: int, tipo: str = "reuniao"
) -> int:
    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data={"tipo": tipo, "data_evento": "2024-05-10", "descricao": f"Evento {tipo}"},
        headers=headers,
        content_type="multipart/form-data",
    )
    assert response.status_code == 201
    return get_success_data(response)["id"]


def test_delete_evento_as_admin(
    client: FlaskClient, auth_headers: dict[str, str], sample_caso_data: dict[str, Any]
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento_id = _criar_evento(client, auth_headers, caso_id)

    response = client.delete(f"/api/caso/{caso_id}/eventos/{evento_id}", headers=auth_headers)
    assert response.status_code == 200

    # Sai da listagem, mas continua acessível por id como inativo.
    listagem = get_success_data(client.get(f"/api/caso/{caso_id}/eventos", headers=auth_headers))
    assert evento_id not in [e["id"] for e in listagem["items"]]

    detalhe = get_success_data(
        client.get(f"/api/caso/{caso_id}/eventos/{evento_id}", headers=auth_headers)
    )
    assert detalhe["status"] is False

    # Excluir de novo devolve 404.
    response = client.delete(f"/api/caso/{caso_id}/eventos/{evento_id}", headers=auth_headers)
    assert response.status_code == 404


def test_delete_evento_by_creator(
    client: FlaskClient,
    auth_headers: dict[str, str],
    non_admin_auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento_id = _criar_evento(client, non_admin_auth_headers, caso_id)

    response = client.delete(
        f"/api/caso/{caso_id}/eventos/{evento_id}", headers=non_admin_auth_headers
    )
    assert response.status_code == 200


def test_delete_evento_by_other_user_is_forbidden(
    client: FlaskClient,
    auth_headers: dict[str, str],
    non_admin_auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento_id = _criar_evento(client, auth_headers, caso_id)

    response = client.delete(
        f"/api/caso/{caso_id}/eventos/{evento_id}", headers=non_admin_auth_headers
    )
    assert response.status_code == 403

    listagem = get_success_data(client.get(f"/api/caso/{caso_id}/eventos", headers=auth_headers))
    assert evento_id in [e["id"] for e in listagem["items"]]


def test_delete_evento_wrong_caso_returns_404(
    client: FlaskClient, auth_headers: dict[str, str], sample_caso_data: dict[str, Any]
) -> None:
    caso_a = _criar_caso(client, auth_headers, sample_caso_data)
    caso_b = _criar_caso(client, auth_headers, sample_caso_data)
    evento_id = _criar_evento(client, auth_headers, caso_a)

    response = client.delete(f"/api/caso/{caso_b}/eventos/{evento_id}", headers=auth_headers)
    assert response.status_code == 404


def test_filter_eventos_by_tipo(
    client: FlaskClient, auth_headers: dict[str, str], sample_caso_data: dict[str, Any]
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    reuniao = _criar_evento(client, auth_headers, caso_id, tipo="reuniao")
    audiencia = _criar_evento(client, auth_headers, caso_id, tipo="audencia")
    _criar_evento(client, auth_headers, caso_id, tipo="reuniao")

    todos = get_success_data(client.get(f"/api/caso/{caso_id}/eventos", headers=auth_headers))
    assert todos["total"] == 3

    so_reuniao = get_success_data(
        client.get(f"/api/caso/{caso_id}/eventos?tipo=reuniao", headers=auth_headers)
    )
    assert so_reuniao["total"] == 2
    assert reuniao in [e["id"] for e in so_reuniao["items"]]
    assert audiencia not in [e["id"] for e in so_reuniao["items"]]

    # "todos" é tratado como ausência de filtro.
    assert (
        get_success_data(
            client.get(f"/api/caso/{caso_id}/eventos?tipo=todos", headers=auth_headers)
        )["total"]
        == 3
    )


def test_list_eventos_exposes_creator_id(
    client: FlaskClient, auth_headers: dict[str, str], sample_caso_data: dict[str, Any]
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    _criar_evento(client, auth_headers, caso_id)

    listagem = get_success_data(client.get(f"/api/caso/{caso_id}/eventos", headers=auth_headers))
    assert listagem["items"][0]["id_criado_por"] == 1
    assert listagem["items"][0]["descricao"] == "Evento reuniao"


def test_evento_herda_a_unidade_do_caso(
    client: FlaskClient,
    auth_headers_nl: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """O evento nasce na unidade do caso, não na unidade padrão."""
    caso_id = _criar_caso(client, auth_headers_nl, sample_caso_data)
    evento_id = _criar_evento(client, auth_headers_nl, caso_id)

    detalhe = get_success_data(
        client.get(f"/api/caso/{caso_id}/eventos/{evento_id}", headers=auth_headers_nl)
    )
    assert detalhe["unidade_id"] == 2


def test_agenda_de_caso_de_outra_unidade_nao_aparece(
    client: FlaskClient,
    auth_headers: dict[str, str],
    auth_headers_nl: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Evento de caso da unidade 2 não aparece na agenda da unidade 1, ainda que
    o usuário pertença às duas."""
    caso_nl = _criar_caso(client, auth_headers_nl, sample_caso_data)
    _criar_evento(client, auth_headers_nl, caso_nl)

    assert (
        client.get(f"/api/caso/{caso_nl}/eventos", headers=auth_headers_nl).status_code
        == 200
    )
    assert (
        client.get(f"/api/caso/{caso_nl}/eventos", headers=auth_headers).status_code
        == 404
    )


def test_evento_de_outra_unidade_responde_404(
    client: FlaskClient,
    auth_headers: dict[str, str],
    auth_headers_nl: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Detalhe, edição, exclusão e download de evento de outra unidade dão 404."""
    caso_nl = _criar_caso(client, auth_headers_nl, sample_caso_data)
    evento_id = _criar_evento(client, auth_headers_nl, caso_nl)

    rota = f"/api/caso/{caso_nl}/eventos/{evento_id}"
    assert client.get(rota, headers=auth_headers).status_code == 404
    assert (
        client.put(
            rota,
            data={"descricao": "Tentativa de outra unidade"},
            headers=auth_headers,
            content_type="multipart/form-data",
        ).status_code
        == 404
    )
    assert client.delete(rota, headers=auth_headers).status_code == 404
    assert client.get(f"{rota}/download", headers=auth_headers).status_code == 404


def test_criar_evento_em_caso_de_outra_unidade_responde_404(
    client: FlaskClient,
    auth_headers: dict[str, str],
    auth_headers_nl: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_nl = _criar_caso(client, auth_headers_nl, sample_caso_data)

    response = client.post(
        f"/api/caso/{caso_nl}/eventos",
        data={"tipo": "reuniao", "data_evento": "2024-05-10"},
        headers=auth_headers,
        content_type="multipart/form-data",
    )
    assert response.status_code == 404


# ---------------------------------------------------------------------------
# Anexo do evento na raiz privada (#190)
# ---------------------------------------------------------------------------


def _anexo_do_evento(app: Flask, ref: str) -> bool:
    """O anexo está no volume? O banco guarda só a referência relativa."""
    with app.app_context():
        return private_file_storage.exists("eventos", ref)


def _eventos_no_volume(app: Flask) -> list[str]:
    with app.app_context():
        return sorted(os.listdir(private_file_storage.categoria_dir("eventos")))


def _criar_evento_com_anexo(
    client: FlaskClient,
    headers: dict[str, str],
    caso_id: int,
    conteudo: bytes = b"conteudo do anexo",
    nome: str = "peticao inicial.pdf",
) -> dict[str, Any]:
    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data={
            "tipo": "Juntada",
            "data_evento": "2024-05-10",
            "status": "true",
            "arquivo": (BytesIO(conteudo), nome),
        },
        headers=headers,
        content_type="multipart/form-data",
    )
    assert response.status_code == 201
    return get_success_data(response)


def test_anexo_de_evento_guarda_referencia_relativa(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """A resposta traz a referência, nunca a raiz absoluta do volume."""
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento = _criar_evento_com_anexo(client, auth_headers, caso_id)

    ref = evento["arquivo"]
    assert not os.path.isabs(ref)
    assert "/" not in ref
    assert str(app.config["PRIVATE_FILES_ROOT"]) not in ref
    assert ref.endswith("_peticao_inicial.pdf")
    assert _anexo_do_evento(app, ref)


def test_download_de_evento_devolve_nome_original_e_headers(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento = _criar_evento_com_anexo(client, auth_headers, caso_id, b"miolo do pdf")

    response = client.get(
        f"/api/caso/{caso_id}/eventos/{evento['id']}/download", headers=auth_headers
    )

    assert response.status_code == 200
    assert response.data == b"miolo do pdf"
    assert "peticao_inicial.pdf" in response.headers["Content-Disposition"]
    assert response.headers["Cache-Control"] == "private, no-store"


def test_download_de_evento_exige_autenticacao(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento = _criar_evento_com_anexo(client, auth_headers, caso_id)

    assert (
        client.get(f"/api/caso/{caso_id}/eventos/{evento['id']}/download").status_code
        == 401
    )


def test_evento_excluido_nao_e_baixavel(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """O soft delete tira o anexo do volume e o download responde 404."""
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento = _criar_evento_com_anexo(client, auth_headers, caso_id)
    ref = evento["arquivo"]

    assert (
        client.delete(
            f"/api/caso/{caso_id}/eventos/{evento['id']}", headers=auth_headers
        ).status_code
        == 200
    )

    assert not _anexo_do_evento(app, ref)
    assert (
        client.get(
            f"/api/caso/{caso_id}/eventos/{evento['id']}/download", headers=auth_headers
        ).status_code
        == 404
    )


def test_put_remove_o_anexo_substituido(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento = _criar_evento_com_anexo(client, auth_headers, caso_id, b"antigo")
    ref_antiga = evento["arquivo"]

    response = client.put(
        f"/api/caso/{caso_id}/eventos/{evento['id']}",
        data={"arquivo": (BytesIO(b"novo"), "substituto.pdf")},
        headers=auth_headers,
        content_type="multipart/form-data",
    )
    assert response.status_code == 200
    ref_nova = get_success_data(response)["arquivo"]

    assert ref_nova != ref_antiga
    assert not _anexo_do_evento(app, ref_antiga)
    assert _anexo_do_evento(app, ref_nova)

    download = client.get(
        f"/api/caso/{caso_id}/eventos/{evento['id']}/download", headers=auth_headers
    )
    assert download.data == b"novo"


def test_upload_de_tipo_nao_permitido_e_recusado(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    antes = _eventos_no_volume(app)

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data={
            "tipo": "Juntada",
            "data_evento": "2024-05-10",
            "arquivo": (BytesIO(b"MZ"), "malicioso.exe"),
        },
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 400
    assert "Tipo de arquivo não permitido" in response.json["error"]["message"]
    assert _eventos_no_volume(app) == antes


def test_upload_de_evento_maior_que_o_limite_e_recusado(
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    grande = BytesIO(b"0" * (10 * 1024 * 1024 + 1024))

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data={
            "tipo": "Juntada",
            "data_evento": "2024-05-10",
            "arquivo": (grande, "grande.pdf"),
        },
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 413
    assert (
        response.json["error"]["message"]
        == "O arquivo excede o tamanho máximo de 10 MB"
    )


def test_validacao_de_tamanho_do_anexo_no_service(app: Flask) -> None:
    """O limite do service, alcançável só por chamada direta.

    Pela API o `MAX_CONTENT_LENGTH` do próprio Flask barra antes, com 413;
    quem chama o service (o migrador, por exemplo) passa por aqui.
    """
    with app.app_context():
        limite = app.config["MAX_CONTENT_LENGTH"]
        arquivo = FileStorage(
            stream=BytesIO(b"0" * (limite + 1)), filename="grande.pdf"
        )
        with pytest.raises(ValidationException) as excinfo:
            EventoService._validar_anexo(arquivo)
    assert "excede o tamanho máximo" in str(excinfo.value)


def test_upload_em_caso_de_outra_unidade_nao_deixa_orfao(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    auth_headers_nl: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    """Acesso negado antes de gravar: nada sobra no volume."""
    caso_nl = _criar_caso(client, auth_headers_nl, sample_caso_data)
    antes = _eventos_no_volume(app)

    response = client.post(
        f"/api/caso/{caso_nl}/eventos",
        data={
            "tipo": "Juntada",
            "data_evento": "2024-05-10",
            "arquivo": (BytesIO(b"conteudo"), "documento.pdf"),
        },
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code == 404
    assert _eventos_no_volume(app) == antes


def test_falha_ao_criar_evento_nao_deixa_anexo_no_volume(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """O registro não nasceu: o anexo recém-gravado não pode ficar."""
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    antes = _eventos_no_volume(app)

    def explode(*args: Any, **kwargs: Any) -> int:
        raise RuntimeError("banco fora do ar")

    monkeypatch.setattr(EventoRepository, "create", explode)

    response = client.post(
        f"/api/caso/{caso_id}/eventos",
        data={
            "tipo": "Juntada",
            "data_evento": "2024-05-10",
            "arquivo": (BytesIO(b"conteudo"), "documento.pdf"),
        },
        headers=auth_headers,
        content_type="multipart/form-data",
    )

    assert response.status_code >= 400
    assert _eventos_no_volume(app) == antes


def test_download_com_anexo_ausente_do_volume(
    app: Flask,
    client: FlaskClient,
    auth_headers: dict[str, str],
    sample_caso_data: dict[str, Any],
) -> None:
    caso_id = _criar_caso(client, auth_headers, sample_caso_data)
    evento = _criar_evento_com_anexo(client, auth_headers, caso_id)

    with app.app_context():
        os.remove(private_file_storage.resolve("eventos", evento["arquivo"]))

    response = client.get(
        f"/api/caso/{caso_id}/eventos/{evento['id']}/download", headers=auth_headers
    )
    assert response.status_code >= 400
    assert "não encontrado no servidor" in response.json["error"]["message"]
