"""alteracao campos assistido

Revision ID: 034c7dd123a0
Revises: 2f22d55a5fcd
Create Date: 2020-06-22 14:36:08.631839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '034c7dd123a0'
down_revision = '2f22d55a5fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_fisica', 'possui_outros_imoveis',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_column('assistidos_pessoa_fisica', 'possui_veiculos_obs')
    op.add_column('assistidos_pessoa_juridica', sa.Column('nascimento_repres_legal', sa.Date(), nullable=True))
    op.add_column('assistidos_pessoa_juridica', sa.Column('rg_repres_legal', sa.String(length=50, collation='latin1_general_ci'), nullable=True))
    op.add_column('assistidos_pessoa_juridica', sa.Column('socios', sa.String(length=1000, collation='latin1_general_ci'), nullable=True))
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_column('assistidos_pessoa_juridica', 'rg')
    op.drop_column('assistidos_pessoa_juridica', 'sexo')
    op.drop_column('assistidos_pessoa_juridica', 'raca')
    op.drop_column('assistidos_pessoa_juridica', 'profissao')
    op.alter_column('usuarios', 'bolsista',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'bolsista',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.add_column('assistidos_pessoa_juridica', sa.Column('profissao', mysql.VARCHAR(collation='latin1_general_ci', length=80), nullable=False))
    op.add_column('assistidos_pessoa_juridica', sa.Column('raca', mysql.VARCHAR(collation='latin1_general_ci', length=20), nullable=False))
    op.add_column('assistidos_pessoa_juridica', sa.Column('sexo', mysql.VARCHAR(collation='latin1_general_ci', length=1), nullable=False))
    op.add_column('assistidos_pessoa_juridica', sa.Column('rg', mysql.VARCHAR(collation='latin1_general_ci', length=50), nullable=False))
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('assistidos_pessoa_juridica', 'socios')
    op.drop_column('assistidos_pessoa_juridica', 'rg_repres_legal')
    op.drop_column('assistidos_pessoa_juridica', 'nascimento_repres_legal')
    op.add_column('assistidos_pessoa_fisica', sa.Column('possui_veiculos_obs', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=True))
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_outros_imoveis',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
