"""novos campos atendido

Revision ID: 083a891be709
Revises: 2f528f3fa4cc
Create Date: 2020-06-15 21:03:33.622815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '083a891be709'
down_revision = '2f528f3fa4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_fisica', 'possui_outros_imoveis',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.add_column('atendidos', sa.Column('atendido_eh_representante', sa.String(length=80, collation='latin1_general_ci'), nullable=True))
    op.add_column('atendidos', sa.Column('cpf_representante_legal', sa.String(length=14, collation='latin1_general_ci'), nullable=True))
    op.add_column('atendidos', sa.Column('existe_pessoa_juridica', sa.String(length=80, collation='latin1_general_ci'), nullable=False))
    op.add_column('atendidos', sa.Column('nome_representante_legal', sa.String(length=80, collation='latin1_general_ci'), nullable=True))
    op.add_column('atendidos', sa.Column('telefone_representante_legal', sa.String(length=18, collation='latin1_general_ci'), nullable=True))
    op.alter_column('usuarios', 'bolsista',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'bolsista',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('atendidos', 'telefone_representante_legal')
    op.drop_column('atendidos', 'nome_representante_legal')
    op.drop_column('atendidos', 'existe_pessoa_juridica')
    op.drop_column('atendidos', 'cpf_representante_legal')
    op.drop_column('atendidos', 'atendido_eh_representante')
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_outros_imoveis',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
