"""criacao coluna status tbl usuario

Revision ID: 0b4b365d1092
Revises: 94da977db68c
Create Date: 2020-07-02 20:58:57.765336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4b365d1092'
down_revision = '94da977db68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'status')
    # ### end Alembic commands ###
