"""tamanho campo ferias tbl usuario

Revision ID: 142e1e6ac8f2
Revises: 3e7d417402b2
Create Date: 2020-06-01 16:10:22.379053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '142e1e6ac8f2'
down_revision = '3e7d417402b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ferias',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               type_=sa.String(length=150, collation='latin1_general_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ferias',
               existing_type=sa.String(length=150, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
