"""Remodelagem e adicão de atendidos_assistidos

Revision ID: 165dc1cb4674
Revises: 
Create Date: 2020-05-27 19:05:50.617728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165dc1cb4674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=45, collation='latin1_general_ci'), nullable=False),
    sa.Column('uf', sa.String(length=2, collation='latin1_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=60, collation='latin1_general_ci'), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=100, collation='latin1_general_ci'), nullable=True),
    sa.Column('numero', sa.String(length=8, collation='latin1_general_ci'), nullable=True),
    sa.Column('complemento', sa.String(length=100, collation='latin1_general_ci'), nullable=True),
    sa.Column('bairro', sa.String(length=100, collation='latin1_general_ci'), nullable=True),
    sa.Column('cep', sa.String(length=9, collation='latin1_general_ci'), nullable=True),
    sa.Column('cidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=14, collation='latin1_general_ci'), nullable=True),
    sa.Column('cnpj', sa.String(length=18, collation='latin1_general_ci'), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=80, collation='latin1_general_ci'), nullable=True),
    sa.Column('telefone', sa.String(length=18, collation='latin1_general_ci'), nullable=False),
    sa.Column('celular', sa.String(length=18, collation='latin1_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('estado_civil', sa.String(length=80), nullable=False),
    sa.Column('area_juridica', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('como_conheceu', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('indicacao_orgao', sa.String(length=80, collation='latin1_general_ci'), nullable=True),
    sa.Column('procurou_outro_local', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('procurou_qual_local', sa.String(length=80, collation='latin1_general_ci'), nullable=True),
    sa.Column('obs', sa.Text(collation='latin1_general_ci'), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('senha', sa.String(length=60, collation='latin1_general_ci'), nullable=False),
    sa.Column('urole', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('nome', sa.String(length=60, collation='latin1_general_ci'), nullable=False),
    sa.Column('sexo', sa.String(length=60, collation='latin1_general_ci'), nullable=False),
    sa.Column('rg', sa.String(length=18, collation='latin1_general_ci'), nullable=False),
    sa.Column('cpf', sa.String(length=14, collation='latin1_general_ci'), nullable=False),
    sa.Column('profissao', sa.String(length=45, collation='latin1_general_ci'), nullable=False),
    sa.Column('estado_civil', sa.String(length=45, collation='latin1_general_ci'), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=18, collation='latin1_general_ci'), nullable=False),
    sa.Column('celular', sa.String(length=18, collation='latin1_general_ci'), nullable=False),
    sa.Column('oab', sa.String(length=30, collation='latin1_general_ci'), nullable=True),
    sa.Column('obs', sa.Text(collation='latin1_general_ci'), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=False),
    sa.Column('criado', sa.DateTime(), nullable=False),
    sa.Column('modificado', sa.DateTime(), nullable=False),
    sa.Column('criadopor', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=45, collation='latin1_general_ci'), nullable=False),
    sa.Column('modificadopor', sa.Integer(), nullable=False),
    sa.Column('bolsista', sa.Boolean(), nullable=False),
    sa.Column('tipo_bolsa', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('horario_atendimento', sa.String(length=30, collation='latin1_general_ci'), nullable=True),
    sa.Column('inicio_bolsa', sa.DateTime(), nullable=True),
    sa.Column('fim_bolsa', sa.DateTime(), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assistidos_pessoa_fisica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_atendido', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1, collation='latin1_general_ci'), nullable=False),
    sa.Column('profissao', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('raca', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('rg', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('grau_instrucao', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('recebe_beneficio', sa.Boolean(), nullable=False),
    sa.Column('situacao_receita', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('contribui_inss', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('qtd_pessoas_moradia', sa.Integer(), nullable=False),
    sa.Column('renda_familiar', sa.Integer(), nullable=False),
    sa.Column('participacao_renda', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('tipo_moradia', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('possui_outros_imoveis', sa.Boolean(), nullable=False),
    sa.Column('possui_veiculos', sa.Boolean(), nullable=False),
    sa.Column('possui_veiculos_obs', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('quantos_veiculos', sa.Integer(), nullable=False),
    sa.Column('ano_veiculo', sa.String(length=5, collation='latin1_general_ci'), nullable=False),
    sa.Column('doenca_grave_familia', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('pessoa_doente', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('pessoa_doente_obs', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('gastos_medicacao', sa.Integer(), nullable=False),
    sa.Column('obs', sa.String(length=1000, collation='latin1_general_ci'), nullable=False),
    sa.ForeignKeyConstraint(['id_atendido'], ['atendidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistidos_pessoa_juridica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_atendido', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1, collation='latin1_general_ci'), nullable=False),
    sa.Column('profissao', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('raca', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('rg', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('situacao_receita', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('enquadramento', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('sede_bh', sa.Boolean(), nullable=False),
    sa.Column('regiao_sede_bh', sa.String(length=50, collation='latin1_general_ci'), nullable=True),
    sa.Column('regiao_sede_outros', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('area_atuacao', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('negocio_nascente', sa.Boolean(), nullable=False),
    sa.Column('orgao_registro', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('faturamento_anual', sa.Integer(), nullable=False),
    sa.Column('ultimo_balanco_neg', sa.String(length=50, collation='latin1_general_ci'), nullable=True),
    sa.Column('resultado_econ_neg', sa.String(length=50, collation='latin1_general_ci'), nullable=True),
    sa.Column('tem_funcionarios', sa.Boolean(), nullable=False),
    sa.Column('qtd_funcionarios', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['id_atendido'], ['atendidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistidos_pessoa_juridica')
    op.drop_table('assistidos_pessoa_fisica')
    op.drop_table('usuarios')
    op.drop_table('atendidos')
    op.drop_table('enderecos')
    op.drop_table('cidades')
    op.drop_table('estados')
    # ### end Alembic commands ###
