"""empty message

Revision ID: 1a649558964c
Revises: 9dae5c4c3cfc
Create Date: 2022-07-23 13:20:39.053615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a649558964c'
down_revision = '9dae5c4c3cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arquivos', 'descricao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=8000),
               type_=sa.String(length=8000, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('arquivos', 'nome',
               existing_type=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               type_=sa.Text(collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('arquivos', 'titulo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=150),
               type_=sa.String(length=150, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('arquivosCaso', 'link_arquivo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=300),
               type_=sa.String(length=300, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistencias_judiciarias', 'areas_atendidas',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'email',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'nome',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=150),
               type_=sa.String(length=150, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'regiao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'telefone',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'ano_veiculo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=5),
               type_=sa.String(length=5, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos', 'beneficio',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               type_=sa.String(length=30, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'contribui_inss',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               type_=sa.String(length=20, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'doenca_grave_familia',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               type_=sa.String(length=20, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'grau_instrucao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'obs',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos', 'participacao_renda',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'pessoa_doente',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos', 'pessoa_doente_obs',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos', 'possui_veiculos_obs',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos', 'profissao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'qual_beneficio',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               type_=sa.String(length=30, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos', 'raca',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               type_=sa.String(length=20, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'rg',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'sexo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1),
               type_=sa.String(length=1, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos', 'tipo_moradia',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'area_atuacao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'enquadramento',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'orgao_registro',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'qtd_funcionarios',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=7),
               type_=sa.String(length=7, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'regiao_sede_bh',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'regiao_sede_outros',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'resultado_econ_neg',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'situacao_receita',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'socios',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'tem_funcionarios',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               type_=sa.String(length=20, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'ultimo_balanco_neg',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'celular',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'cnpj',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'como_conheceu',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'contato_repres_legal',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'cpf',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=14),
               type_=sa.String(length=14, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'cpf_repres_legal',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=14),
               type_=sa.String(length=14, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'email',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'estado_civil',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'indicacao_orgao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'nome',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'nome_repres_legal',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'obs',
               existing_type=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               type_=sa.Text(collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'pj_constituida',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'pretende_constituir_pj',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'procurou_outro_local',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('atendidos', 'procurou_qual_local',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'rg_repres_legal',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'telefone',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('casos', 'area_direito',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('casos', 'descricao',
               existing_type=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               type_=sa.Text(collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('casos', 'justif_indeferimento',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=280),
               type_=sa.String(length=280, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('casos', 'situacao_deferimento',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('casos', 'sub_area',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('dias_marcados_plantao', 'confirmacao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=15),
               type_=sa.String(length=15, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('documentos_roteiro', 'area_direito',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('documentos_roteiro', 'link',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('enderecos', 'bairro',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('enderecos', 'cep',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=9),
               type_=sa.String(length=9, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('enderecos', 'cidade',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('enderecos', 'complemento',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('enderecos', 'estado',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('enderecos', 'logradouro',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('enderecos', 'numero',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=8),
               type_=sa.String(length=8, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('eventos', 'arquivo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               type_=sa.String(length=100, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('eventos', 'descricao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20000),
               type_=sa.String(length=20000, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('eventos', 'tipo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('lembretes', 'descricao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('notificacao', 'acao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=200),
               type_=sa.String(length=200, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('orientacao_juridica', 'area_direito',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('orientacao_juridica', 'descricao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('orientacao_juridica', 'sub_area',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'especie',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=25),
               type_=sa.String(length=25, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('processos', 'identificacao',
               existing_type=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               type_=sa.Text(collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'link',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               type_=sa.String(length=1000, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'obs',
               existing_type=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               type_=sa.Text(collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'posicao_assistido',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=25),
               type_=sa.String(length=25, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'probabilidade',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=25),
               type_=sa.String(length=25, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'vara',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=200),
               type_=sa.String(length=200, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('registro_entrada', 'confirmacao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=15),
               type_=sa.String(length=15, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'celular',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'cert_atuacao_DAJ',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=3),
               type_=sa.String(length=3, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'cpf',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=14),
               type_=sa.String(length=14, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               type_=sa.String(length=80, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'estado_civil',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=45),
               type_=sa.String(length=45, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'ferias',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=150),
               type_=sa.String(length=150, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'horario_atendimento',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               type_=sa.String(length=30, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'matricula',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=45),
               type_=sa.String(length=45, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'nome',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=60),
               type_=sa.String(length=60, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'oab',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               type_=sa.String(length=30, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'obs',
               existing_type=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               type_=sa.Text(collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'profissao',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=45),
               type_=sa.String(length=45, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'rg',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'senha',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=60),
               type_=sa.String(length=60, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'sexo',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=60),
               type_=sa.String(length=60, collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('usuarios', 'suplente',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               type_=sa.String(length=30, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefone',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               type_=sa.String(length=18, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'tipo_bolsa',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'urole',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'urole',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('usuarios', 'tipo_bolsa',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('usuarios', 'telefone',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=True)
    op.alter_column('usuarios', 'suplente',
               existing_type=sa.String(length=30, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('usuarios', 'sexo',
               existing_type=sa.String(length=60, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=60),
               existing_nullable=False)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.String(length=60, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=60),
               existing_nullable=False)
    op.alter_column('usuarios', 'rg',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=False)
    op.alter_column('usuarios', 'profissao',
               existing_type=sa.String(length=45, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=45),
               existing_nullable=False)
    op.alter_column('usuarios', 'obs',
               existing_type=sa.Text(collation='latin1_general_ci'),
               type_=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('usuarios', 'oab',
               existing_type=sa.String(length=30, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.String(length=60, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=60),
               existing_nullable=False)
    op.alter_column('usuarios', 'matricula',
               existing_type=sa.String(length=45, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=45),
               existing_nullable=True)
    op.alter_column('usuarios', 'horario_atendimento',
               existing_type=sa.String(length=30, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('usuarios', 'ferias',
               existing_type=sa.String(length=150, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=150),
               existing_nullable=True)
    op.alter_column('usuarios', 'estado_civil',
               existing_type=sa.String(length=45, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=45),
               existing_nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('usuarios', 'cpf',
               existing_type=sa.String(length=14, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=14),
               existing_nullable=False)
    op.alter_column('usuarios', 'cert_atuacao_DAJ',
               existing_type=sa.String(length=3, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=3),
               existing_nullable=False)
    op.alter_column('usuarios', 'celular',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=False)
    op.alter_column('registro_entrada', 'confirmacao',
               existing_type=sa.String(length=15, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=15),
               existing_nullable=False)
    op.alter_column('processos', 'vara',
               existing_type=sa.String(length=200, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=200),
               existing_nullable=True)
    op.alter_column('processos', 'probabilidade',
               existing_type=sa.String(length=25, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=25),
               existing_nullable=True)
    op.alter_column('processos', 'posicao_assistido',
               existing_type=sa.String(length=25, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=25),
               existing_nullable=True)
    op.alter_column('processos', 'obs',
               existing_type=sa.Text(collation='latin1_general_ci'),
               type_=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'link',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=True)
    op.alter_column('processos', 'identificacao',
               existing_type=sa.Text(collation='latin1_general_ci'),
               type_=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('processos', 'especie',
               existing_type=sa.String(length=25, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=25),
               existing_nullable=False)
    op.alter_column('orientacao_juridica', 'sub_area',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('orientacao_juridica', 'descricao',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=False)
    op.alter_column('orientacao_juridica', 'area_direito',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('notificacao', 'acao',
               existing_type=sa.String(length=200, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=200),
               existing_nullable=False)
    op.alter_column('lembretes', 'descricao',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=False)
    op.alter_column('eventos', 'tipo',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('eventos', 'descricao',
               existing_type=sa.String(length=20000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20000),
               existing_nullable=True)
    op.alter_column('eventos', 'arquivo',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('enderecos', 'numero',
               existing_type=sa.String(length=8, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=8),
               existing_nullable=False)
    op.alter_column('enderecos', 'logradouro',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('enderecos', 'estado',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('enderecos', 'complemento',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('enderecos', 'cidade',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('enderecos', 'cep',
               existing_type=sa.String(length=9, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=9),
               existing_nullable=False)
    op.alter_column('enderecos', 'bairro',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('documentos_roteiro', 'link',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=True)
    op.alter_column('documentos_roteiro', 'area_direito',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('dias_marcados_plantao', 'confirmacao',
               existing_type=sa.String(length=15, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=15),
               existing_nullable=False)
    op.alter_column('casos', 'sub_area',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('casos', 'situacao_deferimento',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('casos', 'justif_indeferimento',
               existing_type=sa.String(length=280, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=280),
               existing_nullable=True)
    op.alter_column('casos', 'descricao',
               existing_type=sa.Text(collation='latin1_general_ci'),
               type_=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('casos', 'area_direito',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('atendidos', 'telefone',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=True)
    op.alter_column('atendidos', 'rg_repres_legal',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('atendidos', 'procurou_qual_local',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=True)
    op.alter_column('atendidos', 'procurou_outro_local',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('atendidos', 'pretende_constituir_pj',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=True)
    op.alter_column('atendidos', 'pj_constituida',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('atendidos', 'obs',
               existing_type=sa.Text(collation='latin1_general_ci'),
               type_=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               existing_nullable=True)
    op.alter_column('atendidos', 'nome_repres_legal',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=True)
    op.alter_column('atendidos', 'nome',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('atendidos', 'indicacao_orgao',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=True)
    op.alter_column('atendidos', 'estado_civil',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('atendidos', 'email',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('atendidos', 'cpf_repres_legal',
               existing_type=sa.String(length=14, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=14),
               existing_nullable=True)
    op.alter_column('atendidos', 'cpf',
               existing_type=sa.String(length=14, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=14),
               existing_nullable=False)
    op.alter_column('atendidos', 'contato_repres_legal',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=True)
    op.alter_column('atendidos', 'como_conheceu',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('atendidos', 'cnpj',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=True)
    op.alter_column('atendidos', 'celular',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'ultimo_balanco_neg',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'tem_funcionarios',
               existing_type=sa.String(length=20, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'socios',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'situacao_receita',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'resultado_econ_neg',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'regiao_sede_outros',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'regiao_sede_bh',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'qtd_funcionarios',
               existing_type=sa.String(length=7, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=7),
               existing_nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'orgao_registro',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'enquadramento',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'area_atuacao',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('assistidos', 'tipo_moradia',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('assistidos', 'sexo',
               existing_type=sa.String(length=1, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1),
               existing_nullable=False)
    op.alter_column('assistidos', 'rg',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=False)
    op.alter_column('assistidos', 'raca',
               existing_type=sa.String(length=20, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               existing_nullable=False)
    op.alter_column('assistidos', 'qual_beneficio',
               existing_type=sa.String(length=30, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               existing_nullable=True)
    op.alter_column('assistidos', 'profissao',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_veiculos_obs',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('assistidos', 'pessoa_doente_obs',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('assistidos', 'pessoa_doente',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=50),
               existing_nullable=True)
    op.alter_column('assistidos', 'participacao_renda',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('assistidos', 'obs',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=True)
    op.alter_column('assistidos', 'grau_instrucao',
               existing_type=sa.String(length=100, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=100),
               existing_nullable=False)
    op.alter_column('assistidos', 'doenca_grave_familia',
               existing_type=sa.String(length=20, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               existing_nullable=False)
    op.alter_column('assistidos', 'contribui_inss',
               existing_type=sa.String(length=20, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=20),
               existing_nullable=False)
    op.alter_column('assistidos', 'beneficio',
               existing_type=sa.String(length=30, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=30),
               existing_nullable=False)
    op.alter_column('assistidos', 'ano_veiculo',
               existing_type=sa.String(length=5, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=5),
               existing_nullable=True)
    op.alter_column('assistencias_judiciarias', 'telefone',
               existing_type=sa.String(length=18, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=18),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'regiao',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'nome',
               existing_type=sa.String(length=150, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=150),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'email',
               existing_type=sa.String(length=80, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('assistencias_judiciarias', 'areas_atendidas',
               existing_type=sa.String(length=1000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=1000),
               existing_nullable=False)
    op.alter_column('arquivosCaso', 'link_arquivo',
               existing_type=sa.String(length=300, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=300),
               existing_nullable=True)
    op.alter_column('arquivos', 'titulo',
               existing_type=sa.String(length=150, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=150),
               existing_nullable=False)
    op.alter_column('arquivos', 'nome',
               existing_type=sa.Text(collation='latin1_general_ci'),
               type_=mysql.TEXT(charset='latin1', collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('arquivos', 'descricao',
               existing_type=sa.String(length=8000, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(charset='latin1', collation='latin1_general_ci', length=8000),
               existing_nullable=True)
    # ### end Alembic commands ###
