"""empty message

Revision ID: 1a9e33d26a93
Revises: 165dc1cb4674
Create Date: 2020-05-29 11:32:49.406707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a9e33d26a93'
down_revision = '165dc1cb4674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_juridica', 'qtd_funcionarios',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=7),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.alter_column('atendidos', 'estado_civil',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atendidos', 'estado_civil',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'qtd_funcionarios',
               existing_type=sa.String(length=7),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
