"""mudanca models usuario,plantao

Revision ID: 2273cbd74827
Revises: 50f5332c137f
Create Date: 2020-06-08 17:32:20.644165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2273cbd74827'
down_revision = '50f5332c137f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atendidos', 'telefone',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=18),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atendidos', 'telefone',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=18),
               nullable=False)
    # ### end Alembic commands ###
