"""mudanca tabelas assistido

Revision ID: 2ee9a443d882
Revises: 98d109cb3403
Create Date: 2020-06-04 15:02:30.702562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ee9a443d882'
down_revision = '98d109cb3403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistidos_pessoa_fisica', sa.Column('beneficio', sa.String(length=30, collation='latin1_general_ci'), nullable=False))
    op.drop_column('assistidos_pessoa_fisica', 'pessoa_doente_obs')
    op.drop_column('assistidos_pessoa_fisica', 'situacao_receita')
    op.drop_column('assistidos_pessoa_fisica', 'recebe_beneficio')
    op.alter_column('assistidos_pessoa_juridica', 'tem_funcionarios',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=20, collation='latin1_general_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_juridica', 'tem_funcionarios',
               existing_type=sa.String(length=20, collation='latin1_general_ci'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.add_column('assistidos_pessoa_fisica', sa.Column('recebe_beneficio', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('assistidos_pessoa_fisica', sa.Column('situacao_receita', mysql.VARCHAR(collation='latin1_general_ci', length=20), nullable=False))
    op.add_column('assistidos_pessoa_fisica', sa.Column('pessoa_doente_obs', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=True))
    op.drop_column('assistidos_pessoa_fisica', 'beneficio')
    # ### end Alembic commands ###
