"""mudanca tbl Atendido

Revision ID: 2f22d55a5fcd
Revises: 083a891be709
Create Date: 2020-06-17 07:52:35.011583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f22d55a5fcd'
down_revision = '083a891be709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atendidos', 'cpf',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=14),
               nullable=False)
    op.drop_index('cpf', table_name='atendidos')
    op.drop_column('atendidos', 'nome_representante_legal')
    op.drop_column('atendidos', 'cpf_representante_legal')
    op.drop_column('atendidos', 'atendido_eh_representante')
    op.drop_column('atendidos', 'existe_pessoa_juridica')
    op.drop_column('atendidos', 'telefone_representante_legal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendidos', sa.Column('telefone_representante_legal', mysql.VARCHAR(collation='latin1_general_ci', length=18), nullable=True))
    op.add_column('atendidos', sa.Column('existe_pessoa_juridica', mysql.VARCHAR(collation='latin1_general_ci', length=80), nullable=False))
    op.add_column('atendidos', sa.Column('atendido_eh_representante', mysql.VARCHAR(collation='latin1_general_ci', length=80), nullable=True))
    op.add_column('atendidos', sa.Column('cpf_representante_legal', mysql.VARCHAR(collation='latin1_general_ci', length=14), nullable=True))
    op.add_column('atendidos', sa.Column('nome_representante_legal', mysql.VARCHAR(collation='latin1_general_ci', length=80), nullable=True))
    op.create_index('cpf', 'atendidos', ['cpf'], unique=True)
    op.alter_column('atendidos', 'cpf',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=14),
               nullable=True)
    # ### end Alembic commands ###
