"""criacao tbl orientacao_juridica

Revision ID: 2f528f3fa4cc
Revises: 2273cbd74827
Create Date: 2020-06-10 16:23:51.802764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f528f3fa4cc'
down_revision = '2273cbd74827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orientacao_juridica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_direito', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('sub_area', sa.String(length=50, collation='latin1_general_ci'), nullable=True),
    sa.Column('descricao', sa.String(length=1000, collation='latin1_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('atendidos', sa.Column('id_orientacaoJuridica', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atendidos', 'orientacao_juridica', ['id_orientacaoJuridica'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atendidos', type_='foreignkey')
    op.drop_column('atendidos', 'id_orientacaoJuridica')
    op.drop_table('orientacao_juridica')
    # ### end Alembic commands ###
