"""tamanho campo ferias tbl usuario

Revision ID: 3e7d417402b2
Revises: 7a21dfdf8520
Create Date: 2020-06-01 15:00:59.387094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e7d417402b2'
down_revision = '7a21dfdf8520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ferias',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=10),
               type_=sa.String(length=50, collation='latin1_general_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'ferias',
               existing_type=sa.String(length=50, collation='latin1_general_ci'),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
