"""mudanca models usuario,plantao

Revision ID: 50f5332c137f
Revises: b649a9e04d59
Create Date: 2020-06-08 17:28:28.959421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50f5332c137f'
down_revision = 'b649a9e04d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enderecos', 'bairro',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=False)
    op.alter_column('enderecos', 'cep',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=9),
               nullable=False)
    op.alter_column('enderecos', 'logradouro',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=False)
    op.alter_column('enderecos', 'numero',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=8),
               nullable=False)
    op.alter_column('usuarios', 'telefone',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=18),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'telefone',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=18),
               nullable=False)
    op.alter_column('enderecos', 'numero',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=8),
               nullable=True)
    op.alter_column('enderecos', 'logradouro',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=True)
    op.alter_column('enderecos', 'cep',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=9),
               nullable=True)
    op.alter_column('enderecos', 'bairro',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###
