"""remoção de nullable

Revision ID: 7a21dfdf8520
Revises: 6bd5fa1902be
Create Date: 2020-05-31 16:56:43.623541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a21dfdf8520'
down_revision = '6bd5fa1902be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_fisica', 'possui_outros_imoveis',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'recebe_beneficio',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'tem_funcionarios',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('usuarios', 'bolsista',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('usuarios', 'tipo_bolsa',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'tipo_bolsa',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               nullable=False)
    op.alter_column('usuarios', 'bolsista',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'tem_funcionarios',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'recebe_beneficio',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_outros_imoveis',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
