"""atualizando_ate_sprint_16

Revision ID: 7ac88bb3cb96
Revises: 20e70d03ed44
Create Date: 2020-09-10 21:44:14.154078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac88bb3cb96'
down_revision = '20e70d03ed44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('descricao', sa.String(length=1000, collation='latin1_general_ci'), nullable=True),
    sa.Column('arquivo', sa.String(length=100, collation='latin1_general_ci'), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('id_criado_por', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_caso'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['id_criado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_caso'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lembretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_lembrete', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=1000, collation='latin1_general_ci'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_caso'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=25, collation='latin1_general_ci'), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('identificacao', sa.Text(collation='latin1_general_ci'), nullable=True),
    sa.Column('vara', sa.String(length=200, collation='latin1_general_ci'), nullable=True),
    sa.Column('link', sa.String(length=1000, collation='latin1_general_ci'), nullable=True),
    sa.Column('probabilidade', sa.String(length=25, collation='latin1_general_ci'), nullable=True),
    sa.Column('posicao_assistido', sa.String(length=25, collation='latin1_general_ci'), nullable=True),
    sa.Column('valor_causa_inicial', sa.Integer(), nullable=True),
    sa.Column('valor_causa_atual', sa.Integer(), nullable=True),
    sa.Column('data_distribuicao', sa.Date(), nullable=True),
    sa.Column('data_transito_em_julgado', sa.Date(), nullable=True),
    sa.Column('obs', sa.Text(collation='latin1_general_ci'), nullable=True),
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_caso'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('casos', sa.Column('id_estagiario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'casos', 'usuarios', ['id_estagiario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'casos', type_='foreignkey')
    op.drop_column('casos', 'id_estagiario')
    op.drop_table('processos')
    op.drop_table('lembretes')
    op.drop_table('historicos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
