"""observacao pessoa doente

Revision ID: 94da977db68c
Revises: b3799b54e7e6
Create Date: 2020-07-01 21:06:01.229786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94da977db68c'
down_revision = 'b3799b54e7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistidos', sa.Column('pessoa_doente_obs', sa.String(length=100, collation='latin1_general_ci'), nullable=True))
    op.alter_column('assistidos', 'possui_outros_imoveis',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_veiculos',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('usuarios', 'bolsista',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'bolsista',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_veiculos',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_outros_imoveis',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('assistidos', 'pessoa_doente_obs')
    # ### end Alembic commands ###
