"""mudanca tbl Atendido

Revision ID: 98d109cb3403
Revises: 142e1e6ac8f2
Create Date: 2020-06-02 16:42:04.730527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98d109cb3403'
down_revision = '142e1e6ac8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistidos_pessoa_fisica', sa.Column('situacao_receita', sa.String(length=20, collation='latin1_general_ci'), nullable=False))
    op.drop_column('atendidos', 'endereco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendidos', sa.Column('endereco', mysql.VARCHAR(collation='latin1_general_ci', length=80), nullable=True))
    op.drop_column('assistidos_pessoa_fisica', 'situacao_receita')
    # ### end Alembic commands ###
