"""empty message

Revision ID: a7f02b44889d
Revises: 034c7dd123a0
Create Date: 2020-06-22 16:11:37.559669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7f02b44889d'
down_revision = '034c7dd123a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_atendido', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1, collation='latin1_general_ci'), nullable=False),
    sa.Column('profissao', sa.String(length=80, collation='latin1_general_ci'), nullable=False),
    sa.Column('raca', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('rg', sa.String(length=50, collation='latin1_general_ci'), nullable=False),
    sa.Column('grau_instrucao', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('beneficio', sa.String(length=30, collation='latin1_general_ci'), nullable=False),
    sa.Column('contribui_inss', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('qtd_pessoas_moradia', sa.Integer(), nullable=False),
    sa.Column('renda_familiar', sa.Integer(), nullable=False),
    sa.Column('participacao_renda', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('tipo_moradia', sa.String(length=100, collation='latin1_general_ci'), nullable=False),
    sa.Column('possui_outros_imoveis', sa.Boolean(), nullable=False),
    sa.Column('possui_veiculos', sa.Boolean(), nullable=False),
    sa.Column('quantos_veiculos', sa.Integer(), nullable=True),
    sa.Column('ano_veiculo', sa.String(length=5, collation='latin1_general_ci'), nullable=True),
    sa.Column('doenca_grave_familia', sa.String(length=20, collation='latin1_general_ci'), nullable=False),
    sa.Column('pessoa_doente', sa.String(length=50, collation='latin1_general_ci'), nullable=True),
    sa.Column('gastos_medicacao', sa.Integer(), nullable=True),
    sa.Column('obs', sa.String(length=1000, collation='latin1_general_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_atendido'], ['atendidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assistidos_pessoa_fisica')
    op.add_column('assistidos_pessoa_juridica', sa.Column('id_assistido', sa.Integer(), nullable=True))
    op.drop_constraint('assistidos_pessoa_juridica_ibfk_1', 'assistidos_pessoa_juridica', type_='foreignkey')
    op.create_foreign_key(None, 'assistidos_pessoa_juridica', 'assistidos', ['id_assistido'], ['id'])
    op.drop_column('assistidos_pessoa_juridica', 'id_atendido')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistidos_pessoa_juridica', sa.Column('id_atendido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assistidos_pessoa_juridica', type_='foreignkey')
    op.create_foreign_key('assistidos_pessoa_juridica_ibfk_1', 'assistidos_pessoa_juridica', 'atendidos', ['id_atendido'], ['id'])
    op.drop_column('assistidos_pessoa_juridica', 'id_assistido')
    op.create_table('assistidos_pessoa_fisica',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_atendido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sexo', mysql.VARCHAR(collation='latin1_general_ci', length=1), nullable=False),
    sa.Column('profissao', mysql.VARCHAR(collation='latin1_general_ci', length=80), nullable=False),
    sa.Column('raca', mysql.VARCHAR(collation='latin1_general_ci', length=20), nullable=False),
    sa.Column('rg', mysql.VARCHAR(collation='latin1_general_ci', length=50), nullable=False),
    sa.Column('grau_instrucao', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=False),
    sa.Column('salario', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('contribui_inss', mysql.VARCHAR(collation='latin1_general_ci', length=20), nullable=False),
    sa.Column('qtd_pessoas_moradia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('renda_familiar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('participacao_renda', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=False),
    sa.Column('tipo_moradia', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=False),
    sa.Column('possui_outros_imoveis', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('possui_veiculos', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('quantos_veiculos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ano_veiculo', mysql.VARCHAR(collation='latin1_general_ci', length=5), nullable=True),
    sa.Column('doenca_grave_familia', mysql.VARCHAR(collation='latin1_general_ci', length=20), nullable=False),
    sa.Column('pessoa_doente', mysql.VARCHAR(collation='latin1_general_ci', length=50), nullable=True),
    sa.Column('gastos_medicacao', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('obs', mysql.VARCHAR(collation='latin1_general_ci', length=1000), nullable=True),
    sa.Column('beneficio', mysql.VARCHAR(collation='latin1_general_ci', length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_atendido'], ['atendidos.id'], name='assistidos_pessoa_fisica_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_general_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('assistidos')
    # ### end Alembic commands ###
