"""atualizando_ate_sprint_30

Revision ID: b119a64010d9
Revises: db2e966ccbbe
Create Date: 2020-12-11 17:41:46.746176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b119a64010d9'
down_revision = 'db2e966ccbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150, collation='latin1_general_ci'), nullable=False),
    sa.Column('descricao', sa.String(length=8000, collation='latin1_general_ci'), nullable=True),
    sa.Column('nome', sa.Text(collation='latin1_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dias_plantao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dias_marcados_plantao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_marcada', sa.Date(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('casos', sa.Column('id_colaborador', sa.Integer(), nullable=True))
    op.add_column('casos', sa.Column('numero_ultimo_processo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'casos', 'usuarios', ['id_colaborador'], ['id'])
    op.add_column('eventos', sa.Column('id_usuario_responsavel', sa.Integer(), nullable=True))
    op.alter_column('eventos', 'data_evento',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_foreign_key(None, 'eventos', 'usuarios', ['id_usuario_responsavel'], ['id'])
    op.create_unique_constraint(None, 'processos', ['numero'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processos', type_='unique')
    op.drop_constraint(None, 'eventos', type_='foreignkey')
    op.alter_column('eventos', 'data_evento',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.drop_column('eventos', 'id_usuario_responsavel')
    op.drop_constraint(None, 'casos', type_='foreignkey')
    op.drop_column('casos', 'numero_ultimo_processo')
    op.drop_column('casos', 'id_colaborador')
    op.drop_table('dias_marcados_plantao')
    op.drop_table('plantao')
    op.drop_table('dias_plantao')
    op.drop_table('arquivos')
    # ### end Alembic commands ###
