"""campos representante legal

Revision ID: b3799b54e7e6
Revises: a7f02b44889d
Create Date: 2020-06-25 15:37:16.636461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3799b54e7e6'
down_revision = 'a7f02b44889d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos', 'possui_outros_imoveis',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_veiculos',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_column('assistidos_pessoa_juridica', 'nascimento_repres_legal')
    op.drop_column('assistidos_pessoa_juridica', 'rg_repres_legal')
    op.add_column('atendidos', sa.Column('nascimento_repres_legal', sa.Date(), nullable=True))
    op.add_column('atendidos', sa.Column('rg_repres_legal', sa.String(length=50, collation='latin1_general_ci'), nullable=True))
    op.alter_column('usuarios', 'bolsista',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'bolsista',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('atendidos', 'rg_repres_legal')
    op.drop_column('atendidos', 'nascimento_repres_legal')
    op.add_column('assistidos_pessoa_juridica', sa.Column('rg_repres_legal', mysql.VARCHAR(collation='latin1_general_ci', length=50), nullable=True))
    op.add_column('assistidos_pessoa_juridica', sa.Column('nascimento_repres_legal', sa.DATE(), nullable=True))
    op.alter_column('assistidos_pessoa_juridica', 'sede_bh',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos_pessoa_juridica', 'negocio_nascente',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_veiculos',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('assistidos', 'possui_outros_imoveis',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
