"""mudanca nullables tbl assistidoPessoaFisica

Revision ID: b649a9e04d59
Revises: f0de042e593c
Create Date: 2020-06-05 20:27:21.375207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b649a9e04d59'
down_revision = 'f0de042e593c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_fisica', 'gastos_medicacao',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_fisica', 'gastos_medicacao',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
