"""mudanca tbl assistido fisico

Revision ID: c853607bf87a
Revises: 08ab4edf9e63
Create Date: 2020-06-04 15:49:33.616063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c853607bf87a'
down_revision = '08ab4edf9e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_juridica', 'faturamento_anual',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=10),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_juridica', 'faturamento_anual',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
