"""atualizando_ate_sprint_20

Revision ID: db2e966ccbbe
Revises: 7ac88bb3cb96
Create Date: 2020-10-13 22:35:49.934611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db2e966ccbbe'
down_revision = '7ac88bb3cb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lembretes', sa.Column('data_criacao', sa.DateTime(), nullable=False))
    op.add_column('lembretes', sa.Column('id_do_criador', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'lembretes', 'usuarios', ['id_do_criador'], ['id'])
    op.add_column('processos', sa.Column('id_criado_por', sa.Integer(), server_default='1', nullable=False))
    op.add_column('processos', sa.Column('status', sa.Boolean(), nullable=False))
    op.alter_column('processos', 'especie',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=25),
               nullable=False)
    op.create_foreign_key(None, 'processos', 'usuarios', ['id_criado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processos', type_='foreignkey')
    op.alter_column('processos', 'especie',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=25),
               nullable=True)
    op.drop_column('processos', 'status')
    op.drop_column('processos', 'id_criado_por')
    op.drop_constraint(None, 'lembretes', type_='foreignkey')
    op.drop_column('lembretes', 'id_do_criador')
    op.drop_column('lembretes', 'data_criacao')
    # ### end Alembic commands ###
