"""mudanca nullables tbls assistidos

Revision ID: f0de042e593c
Revises: c853607bf87a
Create Date: 2020-06-05 00:07:09.690375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0de042e593c'
down_revision = 'c853607bf87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_fisica', 'ano_veiculo',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=5),
               nullable=True)
    op.alter_column('assistidos_pessoa_fisica', 'obs',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=1000),
               nullable=True)
    op.alter_column('assistidos_pessoa_fisica', 'pessoa_doente',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               nullable=True)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos_obs',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=True)
    op.alter_column('assistidos_pessoa_fisica', 'quantos_veiculos',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('assistidos_pessoa_juridica', 'regiao_sede_outros',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistidos_pessoa_juridica', 'regiao_sede_outros',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'quantos_veiculos',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'possui_veiculos_obs',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'pessoa_doente',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'obs',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=1000),
               nullable=False)
    op.alter_column('assistidos_pessoa_fisica', 'ano_veiculo',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=5),
               nullable=False)
    # ### end Alembic commands ###
