name: Deploy to QA VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.QA_SSH_HOST }}
          username: ${{ vars.QA_SSH_USERNAME }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/tmp/gestaolegal/"

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.QA_SSH_HOST }}
          username: ${{ vars.QA_SSH_USERNAME }}
          key: ${{ secrets.QA_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            cd /tmp/gestaolegal

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            IMAGE_TAG="latest"
            if [[ "${{ github.ref_name }}" != "master" ]]; then
              IMAGE_TAG="${{ github.ref_name }}"
            fi

            export DOCKER_IMAGE="ghcr.io/${{ github.repository_owner }}/gestaolegal:${IMAGE_TAG}"

            docker compose pull
            docker compose up -d --force-recreate
            make initialize_environment

            # HACK: Workaround so this deployment will work on temporary QA VPS
            docker network connect caddy_reverse-proxy gestaolegal-app_gl-1
